sudo: false
language: node_js
node_js:
  - lts/*
  - 12

cache: yarn

notifications:
  email: false

install: yarn install --frozen-lockfile --non-interactive

stages:
  - test
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
      on:
        branch: master
